CREATE TABLE webhook_endpoints (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant          TEXT NOT NULL,
    repo            TEXT NOT NULL,
    url             TEXT NOT NULL,
    secret          TEXT NOT NULL,
    event_mask      INTEGER NOT NULL,
    active          INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
    created_at      INTEGER NOT NULL,
    UNIQUE (tenant, repo, url),
    FOREIGN KEY (tenant, repo) REFERENCES repos(tenant, name) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX webhook_endpoints_by_repo ON webhook_endpoints (tenant, repo, active);

CREATE TABLE webhook_deliveries (
    id                TEXT PRIMARY KEY,
    endpoint_id       BIGINT NOT NULL,
    event_type        TEXT NOT NULL,
    payload_json      BYTEA NOT NULL,
    status            TEXT NOT NULL,
    attempts          INTEGER NOT NULL DEFAULT 0,
    next_attempt_at   INTEGER NOT NULL,
    last_attempt_at   INTEGER,
    last_status_code  INTEGER,
    last_error        TEXT,
    created_at        INTEGER NOT NULL,
    delivered_at      INTEGER,
    FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoints(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX webhook_deliveries_due ON webhook_deliveries (status, next_attempt_at)
    WHERE status = 'pending';

INSERT INTO schema_version (version, applied_at) VALUES (6, EXTRACT(EPOCH FROM now())::bigint);
