#!/usr/bin/env bash
#
# license-check.sh — dependency-license guard + NOTICE/THIRD_PARTY_LICENSES generator.
#
# bucketvcs ships Apache-2.0. Every Go module statically linked into the
# `bucketvcs` binary must therefore carry a permissive license (Apache-2.0,
# BSD, MIT, ISC), and its attribution must be reproduced. This script is the
# single source of truth for both:
#
#   generate  Regenerate NOTICE and THIRD_PARTY_LICENSES from the linked deps.
#   check     CI guard. Fails if (1) any linked dep's license is outside the
#             permissive allowlist (or missing/unrecognized), or (2) the
#             committed NOTICE / THIRD_PARTY_LICENSES drift from a fresh
#             regeneration (i.e. someone changed deps without running generate).
#
# The module set is scoped to what `./cmd/bucketvcs` actually links (not the
# full module graph), pinned to linux/amd64 for reproducibility across machines.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export LC_ALL=C
# Pin the platform so `generate` and `check` agree regardless of the host OS.
export GOOS=linux GOARCH=amd64

ALLOWED="Apache-2.0 BSD MIT ISC"
NOTICE_FILE="$ROOT/NOTICE"
TPL_FILE="$ROOT/THIRD_PARTY_LICENSES"

GOMODCACHE="$(go env GOMODCACHE)"

# escape an uppercase module path to its module-cache form (A -> !a).
esc() { sed -E 's/([A-Z])/!\L\1/g' <<<"$1"; }

# print the linked, non-main modules as "path<TAB>version", sorted unique.
linked_modules() {
	go list -deps -f '{{if .Module}}{{.Module.Path}}	{{.Module.Version}}{{end}}' ./cmd/bucketvcs \
		| grep -v '^github.com/bucketvcs/bucketvcs	' \
		| sort -u
}

# module_dir <path> <version> -> module-cache directory.
module_dir() { printf '%s/%s@%s' "$GOMODCACHE" "$(esc "$1")" "$2"; }

# license_file <dir> -> the license file path, by fixed precedence, or empty.
license_file() {
	local d="$1" c cand
	for c in LICENSE LICENSE.txt LICENSE.md LICENCE LICENCE.txt COPYING COPYING.txt; do
		[ -f "$d/$c" ] && { printf '%s' "$d/$c"; return; }
	done
	# fallback: first LICENSE*/COPYING*/LICENCE* match (glob; no pipefail hazard).
	for cand in "$d"/LICENSE* "$d"/COPYING* "$d"/LICENCE*; do
		[ -f "$cand" ] && { printf '%s' "$cand"; return; }
	done
	return 0  # nothing found: empty string, success (caller treats "" as missing)
}

# notice_file <dir> -> the NOTICE file path, or empty. Glob loop (not `ls`) so a
# missing NOTICE is empty, not a pipefail-induced set -e abort.
notice_file() {
	local d="$1" cand
	for cand in "$d"/NOTICE*; do
		[ -f "$cand" ] && { printf '%s' "$cand"; return; }
	done
	return 0  # no NOTICE: empty string, success
}

# classify <license-file> -> Apache-2.0 | BSD | MIT | ISC | UNKNOWN
classify() {
	local f="$1"
	[ -z "$f" ] || [ ! -f "$f" ] && { echo UNKNOWN; return; }
	if grep -q "Apache License" "$f"; then echo Apache-2.0
	elif grep -q "Permission is hereby granted, free of charge" "$f"; then echo MIT
	elif grep -q "with or without fee" "$f"; then echo ISC
	elif grep -q "Redistribution and use in source and binary" "$f"; then echo BSD
	else echo UNKNOWN
	fi
}

is_allowed() { case " $ALLOWED " in *" $1 "*) return 0;; *) return 1;; esac; }

# ---- generators (write to stdout) --------------------------------------------

gen_third_party() {
	cat <<'HDR'
THIRD-PARTY SOFTWARE LICENSES
=============================

bucketvcs is distributed as compiled binaries that statically link the Go
modules listed below. Each module is reproduced here with its full license
text, as required by the respective licenses (Apache-2.0 section 4, and the
copyright-notice retention clauses of the BSD, MIT, and ISC licenses).

This file is generated by scripts/license-check.sh from the dependency set of
./cmd/bucketvcs. Run `scripts/license-check.sh generate` to refresh it. See
NOTICE for the attribution notices that accompany the Apache-2.0 components.

HDR
	local path ver dir f t
	while IFS=$'\t' read -r path ver; do
		[ -z "$path" ] && continue
		dir="$(module_dir "$path" "$ver")"
		f="$(license_file "$dir")"
		t="$(classify "$f")"
		echo "================================================================================"
		echo "$path  $ver"
		echo "License: $t"
		echo "================================================================================"
		echo
		cat "$f"
		echo
	done < <(linked_modules)
}

gen_notice() {
	cat <<'HDR'
bucketvcs
Copyright 2026 Eran Sandler

This product is licensed under the Apache License, Version 2.0 (see LICENSE).

This product includes third-party software, statically linked into its
compiled binaries. The full text of every dependency's license is reproduced
in THIRD_PARTY_LICENSES; the dependency set is permissive throughout
(Apache-2.0, BSD, MIT, ISC).

The following bundled components ship their own NOTICE file, reproduced here
verbatim as required by Apache License 2.0 section 4(d):

HDR
	local path ver dir n
	while IFS=$'\t' read -r path ver; do
		[ -z "$path" ] && continue
		dir="$(module_dir "$path" "$ver")"
		n="$(notice_file "$dir")"
		[ -z "$n" ] && continue
		echo "--------------------------------------------------------------------------------"
		echo "$path  $ver"
		echo "--------------------------------------------------------------------------------"
		echo
		cat "$n"
		echo
	done < <(linked_modules)
}

# ---- modes -------------------------------------------------------------------

do_generate() {
	gen_third_party > "$TPL_FILE"
	gen_notice > "$NOTICE_FILE"
	echo "generated NOTICE + THIRD_PARTY_LICENSES from $(linked_modules | wc -l | tr -d ' ') linked modules"
}

do_check() {
	local rc=0 path ver dir f t violations=0 total=0

	# (1) allowlist enforcement
	while IFS=$'\t' read -r path ver; do
		[ -z "$path" ] && continue
		total=$((total+1))
		dir="$(module_dir "$path" "$ver")"
		f="$(license_file "$dir")"
		if [ -z "$f" ]; then
			echo "✗ $path $ver — NO license file found in module cache"
			violations=$((violations+1)); continue
		fi
		t="$(classify "$f")"
		if ! is_allowed "$t"; then
			echo "✗ $path $ver — license '$t' is not in the permissive allowlist ($ALLOWED)"
			violations=$((violations+1))
		fi
	done < <(linked_modules)

	if [ "$violations" -ne 0 ]; then
		echo ""
		echo "license-check: $violations of $total linked modules failed the allowlist."
		echo "bucketvcs ships Apache-2.0; all linked dependencies must be permissive."
		echo "If a new dependency is genuinely acceptable, review it and add its"
		echo "license to ALLOWED in scripts/license-check.sh (with justification)."
		rc=1
	else
		echo "✓ allowlist: all $total linked modules are permissive ($ALLOWED)"
	fi

	# (2) drift detection — committed files must match a fresh regeneration
	local tmp_tpl tmp_notice
	tmp_tpl="$(mktemp)"; tmp_notice="$(mktemp)"
	trap 'rm -f "$tmp_tpl" "$tmp_notice"' RETURN
	gen_third_party > "$tmp_tpl"
	gen_notice > "$tmp_notice"
	if ! diff -q "$tmp_tpl" "$TPL_FILE" >/dev/null; then
		echo "✗ THIRD_PARTY_LICENSES is stale — run: scripts/license-check.sh generate"
		rc=1
	else
		echo "✓ THIRD_PARTY_LICENSES is up to date"
	fi
	if ! diff -q "$tmp_notice" "$NOTICE_FILE" >/dev/null; then
		echo "✗ NOTICE is stale — run: scripts/license-check.sh generate"
		rc=1
	else
		echo "✓ NOTICE is up to date"
	fi

	return $rc
}

case "${1:-check}" in
	generate) do_generate ;;
	check)    do_check ;;
	*) echo "usage: $0 {generate|check}" >&2; exit 2 ;;
esac
